# Numpy

# TODO

- list to numpy
- optional param
    - axis = 0: col, 1 is row, since 1 is updown

In [12]:
from IPython.core.interactiveshell import InteractiveShell
get_ipython().ast_node_interactivity = 'all'

# -----Basic------

# Data structure

## matrix

In [1]:
import numpy as np
mat = [
    [1,2,3],
    [4,5,6],
]
mat = np.array(mat)
mat

array([[1, 2, 3],
       [4, 5, 6]])

## vector

In [15]:
v1_list = [1,2,3]
v1 = np.array(v1_list)
v2_list = [3,4,5]
v2 = np.array(v2_list)
v1
v2

array([1, 2, 3])

array([3, 4, 5])

### concatenate

## optional params

### axis

In [58]:
mat
mat.sum(axis=0) # 0, 1 - row and col
mat.sum(axis=1)

array([[1, 2, 3],
       [4, 5, 6]])

array([5, 7, 9])

array([ 6, 15])

# Array manipulation

## Reverse

In [75]:
a = np.array([1, 2, 3])
a[::-1]

array([3, 2, 1])

## vstack

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([[1], [2], [3]])
d = np.array([[4], [5], [6]])

# stack two rows to matrix
np.vstack((a,b)) 
# column vector
c
# stack two column vectors
np.vstack((c,d))

array([[1, 2, 3],
       [4, 5, 6]])

array([[1],
       [2],
       [3]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Seed

In [ ]:
np.random.seed(23)

# Math operation

## Square

In [29]:
v1**2 == np.square(v1)

array([ True,  True,  True])

## Dot product

In [24]:
# The math interpretation
res = 0
for e1, e2 in zip(v1_list, v2_list):
    res += e1 * e2
# dot product, numpy
v1 @ v2 == np.dot(v1, v2) == v1.dot(v2) == res
res


True

26

## Multiplication - element wise, shape problem

 Sx = [1, 10], Sy = [10, 10]

 Sx = [10, 1], Sy = [10, 1]

Sx = [10, 100], Sy = [100, 10]

 Sx = [1, 10, 100], Sy = [1, 1, 1]

 The thrid one throws error beacuse:
 > When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when:   
 they are equal, or one of them is 1

In [7]:
import numpy as np
a = np.random.rand(10, 100)
b = np.random.rand(100,10)
a * b

ValueError: operands could not be broadcast together with shapes (10,100) (100,10) 

In [8]:
import numpy as np
a = np.random.rand(10, 100)
b = np.random.rand(100,10).T
a * b

array([[2.83726067e-01, 3.47383595e-01, 4.32273572e-02, 5.01880382e-02,
        1.12652149e-01, 9.66797795e-01, 2.61795398e-02, 7.04797018e-01,
        6.41873887e-01, 5.42446413e-01, 6.32822025e-02, 2.80557194e-01,
        3.08922573e-01, 1.15798628e-01, 1.60871796e-01, 4.79177237e-02,
        6.28124344e-02, 4.88053948e-02, 5.26593890e-01, 1.86783102e-01,
        3.29910232e-01, 8.44329896e-01, 7.25970737e-01, 1.04770906e-01,
        7.45506465e-01, 3.33627315e-01, 3.97437351e-01, 2.12266425e-02,
        7.11854910e-01, 2.75138902e-01, 5.47465079e-01, 4.70648022e-01,
        7.52371691e-01, 1.89613443e-02, 5.57701673e-01, 2.97450073e-01,
        1.66022607e-02, 2.13705220e-01, 7.52769193e-01, 3.13110337e-02,
        8.13133042e-01, 2.25993549e-01, 7.36894969e-02, 1.84534060e-01,
        7.88772648e-03, 2.73841626e-02, 2.56555506e-01, 1.19146939e-01,
        1.17938634e-01, 2.48544020e-01, 9.71342574e-02, 8.19924978e-02,
        1.05758693e-01, 4.14718234e-01, 4.10727425e-01, 6.216124

### ------Linear algebra-----

## norm

Frobenius Norm

The Frobenius norm is the generalization to $R^2$ of the already known norm function for vectors 

$$\| \vec a \| = \sqrt {{\vec a} \cdot {\vec a}} $$

For a given $R^2$ matrix A, the frobenius norm is defined as:

$$\|\mathrm{A}\|_{F} \equiv \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n}\left|a_{i j}\right|^{2}}$$


In [60]:
np.linalg.norm(mat) == np.sqrt(np.sum(mat**2))

True

## Other

### Get first n column

In [9]:
mat[:, 1] # Get only that particular column
mat[:, 0:1] # Get first n cols

array([2, 5])

array([[1],
       [4]])